# Generated by Django 3.2.9 on 2021-11-25 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvanceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='AdvanceFeature/')),
                ('mirror_image', models.FileField(blank=True, null=True, upload_to='AdvanceFeature/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='CompanyLogo/')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='Feature/')),
                ('mirror_image', models.FileField(blank=True, null=True, upload_to='Feature/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IntegratedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to='IntegratedCompany/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MottoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='PartnerCompany/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.FileField(upload_to='PartnerCompany/')),
                ('link', models.URLField(blank=True, max_length=1000, null=True)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.CharField(max_length=1000)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='WorkingProcess/')),
                ('mirror_image', models.FileField(blank=True, null=True, upload_to='WorkingProcess/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('companymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solution.companymodel')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('image', models.FileField(upload_to='CustomerService/')),
                ('visibility', models.BooleanField(default=False)),
            ],
            bases=('solution.companymodel',),
        ),
    ]
