# Generated by Django 3.2.9 on 2021-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Testimonial/'),
        ),
    ]
