# Generated by Django 3.2.9 on 2021-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=1000)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MottoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('image1', models.FileField(upload_to='AboutImage/')),
                ('image2', models.FileField(upload_to='AboutImage/')),
                ('image3', models.FileField(upload_to='AboutImage/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OurAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('image', models.FileField(upload_to='OurAward/')),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OurStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('designation', models.CharField(max_length=300)),
                ('image', models.FileField(blank=True, upload_to='TeamMember/')),
                ('linkedin', models.URLField(blank=True, max_length=1000, null=True)),
                ('twitter', models.URLField(blank=True, max_length=1000, null=True)),
                ('git', models.URLField(blank=True, max_length=1000, null=True)),
                ('fb', models.URLField(blank=True, max_length=1000, null=True)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
