# Generated by Django 3.2.9 on 2021-11-26 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JoinBenefitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='CareerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('Remote', 'Remote'), ('Desk', 'Desk')], max_length=100)),
                ('job_nature', models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Contractual', 'Contractual')], max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, default='Negotiable', max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, default='Akus', max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.jobtypemodel')),
            ],
        ),
    ]
